# -*- coding: utf-8 -*-
"""Merge_xlsx.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mIGv5S9whPxFTe52MkqEwR4t7k8ST9nt
"""

import glob
import pandas as pd
import os

# Folder path containing the XLSX files
folder_path = '/content/drive/MyDrive/TX/'

# Get a list of XLSX file paths in the folder
xlsx_files = glob.glob(folder_path + '*.xlsx')

# Iterate over the XLSX files and read them into DataFrames
for file_path in xlsx_files:
    # Read the Excel file
    df = pd.read_excel(file_path)

    # Extract the file name without extension
    file_name = os.path.basename(file_path)
    file_name = os.path.splitext(file_name)[0]

    # Add 'file_name' column with the corresponding file name
    df.insert(0, 'file_name', file_name)

    # Save the modified DataFrame to a new Excel file
    new_file_path = folder_path + 'new_' + file_name + '.xlsx'
    df.to_excel(new_file_path, index=False)

####################### Here make sure you set the correct path, where the xlsx files saved in a single folder after the execution of above code.

# Path to the directory containing the Excel files
directory = '/content/drive/MyDrive/TX/final_files/'

# Get a list of all Excel files in the directory
files = glob.glob(directory + '*.xlsx')

# Create an empty DataFrame to store the merged data
merged_data = pd.DataFrame()

# Iterate over each file
for file in files:
    # Read the file into a DataFrame
    df = pd.read_excel(file, header=None)  # Disable header inference

    # Extract the first row as the row heading
    row_heading = df.iloc[0]

    # Set the first row as the column names
    df.columns = row_heading

    # Remove the first row from the DataFrame
    df = df[1:]

    # Add the data to the merged DataFrame
    merged_data = pd.concat([merged_data, df], ignore_index=True)

# Write the merged data to a new Excel file
merged_data.to_excel('merged_file.xlsx', index=False)